SELECT DISTINCT STUDENT_ID, STUDENT_NAME
FROM STUDENT
WHERE STUDENT_ID IN(
    SELECT DISTINCT STUDENT_ID
    FROM (SELECT *,
                DENSE_RANK() OVER(PARTITION BY EXAM_ID ORDER BY SCORE DESC) AS RK1,
                DENSE_RANK() OVER(PARTITION BY EXAM_ID ORDER BY SCORE) AS RK2
           FROM EXAM)
    WHERE RK1 <> 1 AND RK2 <> 1)
                
