SELECT Id, Company, Salary
FROM(SELECT Id, Company, Salary,
ROW_NUMBER () OVER (PARTITIONBY Company ORDERBY Salary) AS RN ,
COUNT(Id) OVER (PARTITIONBY Company)ASCOUNTSFROMEmployee)TWHERERNBETWEENCOUNTS/20ANDCOUNTS/20+1ORDERBY23ASC
